language: node_js
node_js:
  - "6"

before_install:
  - wget https://releases.hashicorp.com/terraform/0.7.7/terraform_0.7.7_linux_amd64.zip
  - unzip terraform_0.7.7_linux_amd64.zip
  - npm i now -g

install:
  - npm install

script:
  - npm test

before_deploy:
  - ./terraform remote config -backend=S3 -backend-config="bucket=$S3_TF_STATE_BUCKET" -backend-config="key=terraform.tfstate" -backend-config="region=$S3_REGION"
  - ./terraform plan -out=terraform.plan
  - ./terraform apply terraform.plan
  - ./terraform remote push

deploy:
  skip_cleanup: true
  provider: script
  script: now -t $NOW_TOKEN -e NODE_ENV=production -e S3_KEY=$AWS_ACCESS_KEY_ID -e S3_TOKEN=$AWS_SECRET_ACCESS_KEY -e S3_BUCKET=$S3_DB_BUCKET
  on:
    branch: master
